---

- name: dependencies
  include: depend.yml

- name: configure
  include: config.yml

- name: service
  include: service.yml

- name: explicit service restart
  notify: restart takuapi
  when: api_taku_service_restart



